### ISSUE TITLE
Build error: error: no such module 'KituraSys' 

### ISSUE THREAD

**Issue by atmamont** [IBM-Swift/Kitura#273]
I'm getting this compile error, but all prerequisites are ok.
I've read manual 10 times. 
P.S. Trying to compile swift project from the command line for the first time.

`--- Running build on Darwin
--- Build scripts directory: .
--- Checking swift version
swift --version
Apple Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)
Target: x86_64-apple-macosx10.9
--- Invoking swift build
swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib
Compiling Swift Module 'KituraNet' (12 sources)
/Users/atMamont/Documents/Xcode Projects/KituraTest/Packages/Kitura-net-0.3.8/Sources/KituraNet/ClientRequest.swift:17:8: error: no such module 'KituraSys'
import KituraSys
       ^
`

**Comment by vadimeisenbergibm** [comment]
I have updated README - please try this dependency in Step 3:
> Now we add Kitura as a dependency for your project (Package.swift):
```swift
 .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 5)
```

**Comment by atmamont** [comment]
I've tried updated 3rd step with the old project - got many errors saying I need to update dependencies.
Then I made new project from the step1 - got the same error: no such module 'KituraSys' import KituraSys ^

**Comment by vadimeisenbergibm** [comment]
Additional change - please replace `import KituraRouter` by `import Kitura` in your current example.
Please run `swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib` and paste the output here.

**Comment by atmamont** [comment]
Done (in main.swift)
But it seems problem happens while building dependencies even before main.swift

--- Running build on Darwin
--- Build scripts directory: .
--- Checking swift version
swift --version
Apple Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)
Target: x86_64-apple-macosx10.9
--- Invoking swift build
swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'BlueSocket' (3 sources)
Compiling Swift Module 'SwiftyJSON' (1 sources)
Compiling Swift Module 'KituraTemplateEngine' (1 sources)
Compiling Swift Module 'KituraSys' (4 sources)
Compiling Swift Module 'KituraNet' (12 sources)
/Users/atMamont/Documents/Xcode Projects/KituraTest/Packages/Kitura-net-0.5.0/Sources/KituraNet/ClientRequest.swift:17:8: error: no such module 'KituraSys'
import KituraSys
       ^

**Comment by vadimeisenbergibm** [comment]
Correct, something strange happens - KituraSys is compiled and it is still not found in Kitura-net.
May I ask you to zip your directory in its current state and attach it to the issue? Or to attach .build/debug.yaml file ?

**Comment by atmamont** [comment]
Sure!

[debug.yaml.zip](https://github.com/IBM-Swift/Kitura/files/170632/debug.yaml.zip)

**Comment by vadimeisenbergibm** [comment]
Thanks, I have found the problem (seems like a bug in `swift build`). It is due to the whitespace in the name of your directory "Xcode Projects". Move your KituraTest to some other directory that does not have spaces in its full path and it should solve this problem.

**Comment by atmamont** [comment]
Thanks!

**Comment by vadimeisenbergibm** [comment]
Submitted bug to Apple - https://bugs.swift.org/browse/SR-928 .
