### ISSUE TITLE
ERROR: SSL_write, code: 336195711

### ISSUE THREAD

**Issue by benedictdelfierro** [IBM-Swift/Kitura#852]
Hi,

I/m encountering this error when I enable TLS in linux 14.04
I'm using swift 3.0.1 and kitura 1.1.2
It's working if TLS is disabled.

VERBOSE: run() Kitura.swift line 71 - Starting Kitura framework... 
 VERBOSE: run() Kitura.swift line 73 - Starting an HTTP Server on port 8090... 
 INFO: listen(on:) HTTPServer.swift line 70 - Listening on port 8090 (delegate: SSLService.SSLService) 
 WARNING: init() ContentType.swift line 44 - Loading embedded MIME types. 
 ERROR: handleWriteHelper() IncomingSocketHandler.swift line 194 - Write to socket (file descriptor 7) failed. Error = Error code: 336195711, ERROR: SSL_write, code: 336195711, reason: bad write retry. 

code:
let myCertPath = "/opt/phoenix/config/certificate.pem"
let myKeyPath = "/opt/phoenix/config/key.pem"

let mySSLConfig = SSLConfig(withCACertificateFilePath: nil, usingCertificateFile: myCertPath, withKeyFile: myKeyPath, usingSelfSignedCerts: true)

Kitura.addHTTPServer(onPort: 8090, with: router, withSSL: mySSLConfig)

**Comment by billabt** [comment]
Fixed in *BlueSSLService v0.11.56*.  Refreshing your dependencies should get the fix.

**Comment by benedictdelfierro** [comment]
BlueSSLService is now in v0.11.56 but still the same error 

ERROR: handleWriteHelper() IncomingSocketHandler.swift line 194 - Write to socket (file descriptor 7) failed. Error = Error code: 336195711, ERROR: SSL_write, code: 336195711, reason: bad write retry.

**Comment by billabt** [comment]
I ran the exact same test here before posting the fix and I can't reproduce it.  The only difference was I was using my certificates and running on Ubuntu 16.04.  Can you provide a bit more information?  What request triggered the error?  Or did the error appear immediately?  If it appeared immediately, it's likely a problem with your certs.  Any more information you can provide would be extremely helpful.  Thanks in advance.

**Comment by billabt** [comment]
Been doing more research into this problem.  Turns out the fix I put in is good but only for *non-blocking sockets*.  I need to make some more changes.

**Comment by billabt** [comment]
The **complete** fix for this is now in.  However, it resulted in a version change for **BlueSSLService** and **BlueSocket**.  Kitura-net depends on these and will need an update to `Package.swift` before the changes will be picked up by Kitura.  I've tested the changes here (again on 16.04) and can not reproduce your problem.  I'd still like to get more information from you regarding what triggered the error.  Thanks.

**Comment by shmuelk** [comment]
Fixed as part of IBM-Swift/Kitura#858 per @billabt.

**Comment by foldericon** [comment]
I'm still having this issue with latest Kitura 1.6.1. However it seems like it only happens when I try to request content over the static file server that is more than 100KB (like bootstrap.min.css). Hope that helps.

**Comment by na-gupta** [comment]
@foldericon This looks to be the same issue as #1036 
I've submitted a pull request (IBM-Swift/BlueSSLService#21) to BlueSSLService to fix the issue. Please let us know if this resolves the issue. Thanks!

**Comment by na-gupta** [comment]
@foldericon This has been fixed in SSLService-0.12.29. Please verify it works ok now by deleting your Packages directory and fetching/building again. Thanks!
